[workspace]
resolver = "2"
members = [
    "crates/core",
    "crates/encoding",
    "crates/bigint",
    "crates/random",
    "crates/prime",
    "crates/xor",
    "crates/aes",
    "crates/rsa",
    "crates/pgp",
    "crates/x25519",
    "crates/hash",
    "crates/sign",
    "crates/padding",
    "crates/my_pgp",
    "bench",
]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.lints.rust]
warnings = "deny"

[workspace.lints.clippy]
all = "deny"
